- name: Copy file to hosts
  hosts: all
  gather_facts: true
  become: false
  tasks:
    - name: Copy file
      copy:
        src: /home/admin/Documents/ansiblefiles/nginx.yml
        dest: /root/musicfiles
